apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-dev-platform
resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - gateway.yaml
  - httproute.yaml
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - api-gateway/networkpolicy.yaml

images:
  - name: web-image
    newName: REPLACE_ME_WEB_IMAGE
  - name: api-gateway-image
    newName: REPLACE_ME_API_GATEWAY_IMAGE

configMapGenerator:
  - name: web-config
    literals:
      - PORT=3000
