apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-dev-platform
resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml

images:
  - name: app-image
    newName: REPLACE_ME_IMAGE

configMapGenerator:
  - name: web-config
    literals:
      - PORT=3000
