apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: web
  annotations:
    iam.gke.io/gcp-service-account: PLACEHOLDER_GSA_EMAIL
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: ai-dev-platform
