Param(
    [string]$RepoSlug = "swb2019/ai-dev-platform",
    [string]$Branch = "main",
    [string]$DistroName = "Ubuntu",
    [int]$WslMemoryGB,
    [int]$WslProcessors,
    [int]$WslSwapGB = 2,
    [switch]$SkipTests,
    [switch]$SkipSetupAll,
    [switch]$SkipDockerInstall,
    [string]$DockerInstallerPath,
    [string]$CursorInstallerPath,
    [string]$WslUserName
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"
$script:RepoRoot = Resolve-Path -Path (Split-Path -Parent $PSCommandPath)

function Write-Section {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Ensure-Administrator {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)) {
        throw "Run this script from an elevated PowerShell session (Run as Administrator)."
    }
}

function Get-HardwareProfile {
    $system = Get-CimInstance -ClassName Win32_ComputerSystem
    $processors = Get-CimInstance -ClassName Win32_Processor
    $totalMemoryGb = [math]::Round(($system.TotalPhysicalMemory / 1GB), 2)
    $logicalCount = ($processors | Measure-Object -Property NumberOfLogicalProcessors -Sum).Sum
    if (-not $logicalCount) {
        $logicalCount = [Environment]::ProcessorCount
    }
    return [PSCustomObject]@{
        TotalMemoryGB     = $totalMemoryGb
        LogicalProcessors = [int]$logicalCount
    }
}

function Get-WslResourcePlan {
    param(
        [double]$TotalMemoryGB,
        [int]$LogicalProcessors,
        [int]$OverrideMemoryGB,
        [int]$OverrideProcessors,
        [int]$SwapGB
    )
    if ($OverrideMemoryGB -gt 0) {
        $memoryGB = $OverrideMemoryGB
    } else {
        $memoryGB = [math]::Floor([math]::Min([math]::Max([math]::Round($TotalMemoryGB * 0.65), 6), $TotalMemoryGB - 4))
        if ($memoryGB -lt 6) {
            $memoryGB = [math]::Max([math]::Floor($TotalMemoryGB / 2), 4)
        }
    }
    if ($memoryGB -ge [math]::Ceiling($TotalMemoryGB)) {
        $memoryGB = [math]::Max([math]::Ceiling($TotalMemoryGB) - 2, 4)
    }
    if ($memoryGB -lt 4) {
        $memoryGB = 4
    }

    if ($OverrideProcessors -gt 0) {
        $cpuCount = $OverrideProcessors
    } else {
        if ($LogicalProcessors -ge 8) {
            $cpuCount = $LogicalProcessors - 2
        } elseif ($LogicalProcessors -ge 4) {
            $cpuCount = $LogicalProcessors - 1
        } else {
            $cpuCount = $LogicalProcessors
        }
    }
    if ($cpuCount -gt $LogicalProcessors) {
        $cpuCount = $LogicalProcessors
    }
    if ($cpuCount -lt 2 -and $LogicalProcessors -ge 2) {
        $cpuCount = 2
    }
    if ($cpuCount -lt 1) {
        $cpuCount = 1
    }

    $swapGB = if ($SwapGB -gt 0) { $SwapGB } else { 2 }

    return [PSCustomObject]@{
        MemoryGB    = [int]$memoryGB
        Processors  = [int]$cpuCount
        SwapGB      = [int]$swapGB
    }
}

function Ensure-WslConfig {
    param(
        [int]$MemoryGB,
        [int]$Processors,
        [int]$SwapGB
    )
    $configPath = Join-Path $env:USERPROFILE ".wslconfig"
    $lines = @(
        "# Generated by BestSetup-AiDevPlatform.ps1"
        "[wsl2]"
        "memory=${MemoryGB}GB"
        "processors=$Processors"
        "swap=${SwapGB}GB"
        "localhostForwarding=true"
        "dnsProxy=true"
        "autoProxy=true"
    )
    $content = ($lines -join "`r`n") + "`r`n"
    $current = $null
    if (Test-Path $configPath) {
        $current = Get-Content -Path $configPath -Raw -ErrorAction SilentlyContinue
    }
    if ($current -eq $content) {
        Write-Host ".wslconfig already matches the desired settings."
        return
    }
    if ($current) {
        $backupPath = "$configPath.bestsetup-backup-$(Get-Date -Format 'yyyyMMddHHmmss')"
        Copy-Item -Path $configPath -Destination $backupPath -Force
        Write-Host ("Existing .wslconfig backed up to {0}" -f $backupPath) -ForegroundColor Yellow
    }
    Set-Content -Path $configPath -Value $content -Encoding UTF8
    Write-Host ".wslconfig updated with tuned WSL2 resources." -ForegroundColor Green
}

function Assert-VirtualizationReadiness {
    Write-Section "Checking virtualization readiness"
    try {
        $info = Get-ComputerInfo -Property HyperVRequirementVirtualizationFirmwareEnabled,HyperVRequirementDataExecutionPreventionAvailable,HyperVRequirementSecondLevelAddressTranslation,HyperVRequirementHyperVFeatureAvailable
    } catch {
        Write-Warning "Unable to query virtualization status automatically ($($_.Exception.Message)). Ensure virtualization is enabled in firmware."
        return
    }
    $alerts = @()
    if ($info.HyperVRequirementVirtualizationFirmwareEnabled -notin @("True", "Yes")) {
        $alerts += "Enable virtualization support (VT-x/AMD-V) in BIOS/UEFI."
    }
    if ($info.HyperVRequirementDataExecutionPreventionAvailable -notin @("True", "Yes")) {
        $alerts += "Enable Data Execution Prevention in firmware."
    }
    if ($info.HyperVRequirementSecondLevelAddressTranslation -notin @("True", "Yes")) {
        $alerts += "CPU must expose SLAT (Extended Page Tables)."
    }
    if ($alerts.Count -eq 0) {
        Write-Host "Hyper-V prerequisites satisfied." -ForegroundColor Green
        return
    }
    foreach ($alert in $alerts) {
        Write-Warning $alert
    }
    Write-Warning "Resolve the virtualization prerequisites above and rerun the script if WSL2 fails to start."
}

function Invoke-WslCommand {
    param(
        [string]$Command
    )
    $output = & wsl.exe -d $DistroName -- bash -lc $Command 2>&1
    $exitCode = $LASTEXITCODE
    return [PSCustomObject]@{
        ExitCode = $exitCode
        Output   = $output
    }
}

function Wait-ForDocker {
    Write-Section "Ensuring Docker daemon is ready"
    foreach ($attempt in 1..60) {
        $result = Invoke-WslCommand -Command "docker info >/dev/null 2>&1"
        if ($result.ExitCode -eq 0) {
            Write-Host "Docker is responsive inside WSL." -ForegroundColor Green
            return
        }
        Start-Sleep -Seconds 5
    }
    throw "Docker Desktop did not report readiness after tuning. Launch Docker manually and re-run the checks."
}

function Tune-DockerResources {
    param(
        [int]$MemoryGB,
        [int]$Processors,
        [int]$SwapGB
    )
    Write-Section "Tuning Docker Desktop resources"
    $settingsPath = Join-Path $env:APPDATA "Docker\settings.json"
    if (-not (Test-Path $settingsPath)) {
        Write-Warning "Docker Desktop settings.json not found; skipping Docker resource tuning."
        return
    }
    try {
        $json = Get-Content -Path $settingsPath -Raw
        $settings = if ([string]::IsNullOrWhiteSpace($json)) { [pscustomobject]@{} } else { $json | ConvertFrom-Json }
    } catch {
        throw "Failed to parse Docker Desktop settings ($($_.Exception.Message))."
    }
    if (-not $settings) {
        $settings = [pscustomobject]@{}
    }
    if (-not ($settings.PSObject.Properties.Name -contains "resources")) {
        $settings | Add-Member -MemberType NoteProperty -Name "resources" -Value ([pscustomobject]@{})
    }
    $resources = $settings.resources
    if (-not $resources) {
        $resources = [pscustomobject]@{}
        $settings.resources = $resources
    }
    $resources.cpus = $Processors
    $resources.memoryMiB = $MemoryGB * 1024
    $resources.swapMiB = $SwapGB * 1024
    if ($resources.PSObject.Properties.Name -contains "swapFileSizeMiB") {
        $resources.swapFileSizeMiB = $SwapGB * 1024
    } else {
        $resources | Add-Member -MemberType NoteProperty -Name "swapFileSizeMiB" -Value ($SwapGB * 1024)
    }
    if (-not ($settings.PSObject.Properties.Name -contains "wslEngineEnabled")) {
        $settings | Add-Member -MemberType NoteProperty -Name "wslEngineEnabled" -Value $true
    } else {
        $settings.wslEngineEnabled = $true
    }
    $settings.autoStart = $true
    $content = ($settings | ConvertTo-Json -Depth 12)
    $backupPath = "$settingsPath.bestsetup-backup-$(Get-Date -Format 'yyyyMMddHHmmss')"
    Copy-Item -Path $settingsPath -Destination $backupPath -Force
    $content | Set-Content -Path $settingsPath -Encoding UTF8
    Write-Host ("Docker Desktop settings updated (backup: {0})." -f $backupPath) -ForegroundColor Green

    $dockerCli = Join-Path $env:ProgramFiles "Docker\Docker\DockerCli.exe"
    $dockerExe = Join-Path $env:ProgramFiles "Docker\Docker\Docker Desktop.exe"
    if (Test-Path $dockerCli) {
        & $dockerCli -Shutdown *> $null
    } else {
        Get-Process -Name "Docker Desktop" -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
    }
    if (Test-Path $dockerExe) {
        Start-Process -FilePath $dockerExe | Out-Null
    }
    Wait-ForDocker
}

function Run-WslStep {
    param(
        [string]$Label,
        [string]$Command
    )
    Write-Section $Label
    $result = Invoke-WslCommand -Command $Command
    if ($result.Output) {
        $result.Output | ForEach-Object { if ($_ -ne "") { Write-Host $_ } }
    }
    if ($result.ExitCode -ne 0) {
        throw ("{0} failed inside WSL (exit {1})." -f $Label, $result.ExitCode)
    }
}

function Clear-DownloadZoneMarkers {
    param([string]$Root)
    if (-not (Test-Path $Root)) {
        return
    }
    Write-Section "Clearing Windows download markers"
    $patterns = @("*.ps1","*.psm1","*.psd1","*.cmd","*.bat","*.exe","*.msi","*.sh")
    $files = Get-ChildItem -LiteralPath $Root -Recurse -File -Include $patterns -ErrorAction SilentlyContinue
    if (-not $files) {
        Write-Host "No download markers detected." -ForegroundColor Green
        return
    }
    $cleared = 0
    foreach ($file in $files) {
        try {
            $stream = Get-Item -LiteralPath $file.FullName -Stream "Zone.Identifier" -ErrorAction SilentlyContinue
            if ($null -ne $stream) {
                Unblock-File -LiteralPath $file.FullName -ErrorAction Stop
                $cleared++
            }
        } catch {
            continue
        }
    }
    if ($cleared -gt 0) {
        Write-Host ("Removed security zone markers from {0} file(s)." -f $cleared) -ForegroundColor Green
    } else {
        Write-Host "No security zone markers required removal." -ForegroundColor Green
    }
}

Ensure-Administrator
Clear-DownloadZoneMarkers -Root $script:RepoRoot
$hardware = Get-HardwareProfile
Write-Section "Host hardware profile"
Write-Host ("Physical memory : {0} GB" -f $hardware.TotalMemoryGB)
Write-Host ("Logical cores   : {0}" -f $hardware.LogicalProcessors)

$plan = Get-WslResourcePlan -TotalMemoryGB $hardware.TotalMemoryGB -LogicalProcessors $hardware.LogicalProcessors -OverrideMemoryGB $WslMemoryGB -OverrideProcessors $WslProcessors -SwapGB $WslSwapGB
Write-Host ("WSL memory      : {0} GB" -f $plan.MemoryGB)
Write-Host ("WSL processors  : {0}" -f $plan.Processors)
Write-Host ("WSL swap        : {0} GB" -f $plan.SwapGB)

Assert-VirtualizationReadiness
Ensure-WslConfig -MemoryGB $plan.MemoryGB -Processors $plan.Processors -SwapGB $plan.SwapGB

Write-Section "Restarting WSL to apply resource limits"
& wsl.exe --shutdown 2>$null

$setupScript = Join-Path $script:RepoRoot "scripts\windows\setup.ps1"
if (-not (Test-Path $setupScript)) {
    throw "Expected bootstrap script not found at $setupScript."
}

$setupArgs = @(
    "-RepoSlug", $RepoSlug,
    "-Branch", $Branch,
    "-DistroName", $DistroName
)
if ($SkipDockerInstall) { $setupArgs += "-SkipDockerInstall" }
if ($SkipSetupAll) { $setupArgs += "-SkipSetupAll" }
if ($DockerInstallerPath) {
    $setupArgs += "-DockerInstallerPath"
    $setupArgs += $DockerInstallerPath
}
if ($CursorInstallerPath) {
    $setupArgs += "-CursorInstallerPath"
    $setupArgs += $CursorInstallerPath
}
if ($WslUserName) {
    $setupArgs += "-WslUserName"
    $setupArgs += $WslUserName
}

Write-Section "Running base Windows bootstrap"
& $setupScript @setupArgs
if ($LASTEXITCODE -ne 0) {
    throw "scripts/windows/setup.ps1 exited with code $LASTEXITCODE."
}

Tune-DockerResources -MemoryGB $plan.MemoryGB -Processors $plan.Processors -SwapGB $plan.SwapGB

if (-not $SkipTests) {
    Run-WslStep -Label "pnpm lint" -Command "cd ~/ai-dev-platform && export CI=1 TURBO_ORIGIN=bestsetup && pnpm lint"
    Run-WslStep -Label "pnpm test (web)" -Command "cd ~/ai-dev-platform && export CI=1 TURBO_ORIGIN=bestsetup && pnpm --filter \"@ai-dev-platform/web\" test -- --runInBand"
    Run-WslStep -Label "Playwright e2e" -Command "cd ~/ai-dev-platform && export CI=1 && pnpm --filter \"@ai-dev-platform/web\" exec playwright test --reporter=line"
} else {
    Write-Section "Test execution skipped by request"
}

Write-Section "Environment ready"
Write-Host "Codex can now run end-to-end tests under WSL2 with tuned resources." -ForegroundColor Green
