apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: web-image
    newName: REGISTRY/ai-dev-platform-staging/web
    newTag: latest
  - name: api-gateway-image
    newName: REGISTRY/ai-dev-platform-staging/api-gateway
    newTag: latest

patchesStrategicMerge:
  - replicas.yaml
  - api-gateway-replicas.yaml
  - service-account-patch.yaml
