apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-runtime
  namespace: ai-dev-platform
  annotations:
    iam.gke.io/gcp-service-account: replace-me-staging-gsa@project-id.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-runtime
  namespace: ai-dev-platform
  annotations:
    iam.gke.io/gcp-service-account: replace-me-staging-api-gsa@project-id.iam.gserviceaccount.com
