name: Task Context Reminder

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure task context updated
        run: |
          if [[ "$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '^config/task-context.json$|^docs/AGENT_HANDBOOK.md$')" == "" ]]; then
            echo "::warning::Reminder: consider updating config/task-context.json and docs/AGENT_HANDBOOK.md to reflect progress." \
            "Include the latest status in your PR description."
          else
            echo "Task context files modified in this PR."
          fi
